Update deploy.yml
Signed-off-by: Gena03 <162874586+Gena03000@users.noreply.github.com>

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,6 +26,12 @@ jobs:
             echo "❌ Invalid PORT: $PORT"
             exit 1
           fi
+- name: ✅ Check Railway token presence
+  run: |
+    if [ -z "${{ secrets.RAILWAY_TOKEN }}" ]; then
+      echo "❌ Railway token is missing"
+      exit 1
+    fi
 
       - name: 📦 Checkout code
         uses: actions/checkout@v4
